config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  devise_for :users
  
  root 'posts#index'
  resources :posts do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :edit, :destroy]
  end
  
  get '/posts/new' => 'posts#create'
  get '/posts/show/:id' => 'posts#show'
  
  get 'mypage' => 'users/edit' # 마이페이지 누르면 정보 수정창으로 가게
  get 'index' => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    mount_uploader :image, ImageUploader
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  mount_uploader :avatar, AvatarUploader
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership!, only: [:destroy, :edit]
    
    def create
        new_comment = Comment.new(content: params[:content],
                                  post_id: params[:post_id],
                                  user_id: current_user.id)
        new_comment.save
        redirect_to :back
    end
    
    def destroy
        @comment.destroy
        redirect_to :back
    end
    
    def edit
    end
    
    private 
    def check_ownership!
        @comment = Comment.find_by(id: params[:id])
        redirect_to root_path if @comment.user.id != current_user.id
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    
    def like_toggle
        like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
        
        if like.nil?
            Like.create(user_id: current_user.id, post_id: params[:post_id])
        else
            like.destroy
        end
        
        redirect_to :back
    end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
    def index   
    end
    
    def edit
        @post = Post.find_by(id: params[:id])
      end
  
  def new
  end
    
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]
  # 로그인한 회원만 할 수 있도록 함
  
  def index
    @posts = Post.all.order('created_at desc').paginate(page: params[:page], per_page: 10)
    @posts_count = current_user.posts.length
    # 사용자의 작성 글 갯수
  end
  
  def new
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, title: params[:title], content: params[:content], image: params[:image])
    if new_post.save
      redirect_to posts_path
    else 
      redirect_to new_post_path
    end
  end
  
  
  def show
    @post = Post.find(params[:id])
  end
  
 
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    @post.title = params[:title]
    @post.content = params[:content]
    @post.image = params[:image]
    
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end
 
 def destroy
    @post.destroy
    redirect_to root_path
 end
 
 private
   def check_ownership
    @post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user_id != current_user.id
   end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Okey-Doggy</title>
  <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />

      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
  <%= csrf_meta_tags %>
  
  
  <style>
    .sign_out {
     text-color: #ffca28;
    }
    
  body {
  font-family:'나눔고딕';
  }
  
  .logo_font {
    font-family:'A북두칠성';
  }
    
    
  </style>
  
</head>


<body>
    
    <nav class="nav-wrapper amber lighten-1">
    <div class="nav-wrapper amber lighten-1" style="width:970px; margin:0 auto;">
      <a href="/" class="brand-logo"><img src="./Logo.png" style="float:middle;width:42px;height:42px;"><span class="logo_font grey-text text-darken-4">&nbsp;&nbsp;Okey-Doggy</span></a>

      <!--웹 형태-->
      <ul class="right hide-on-med-and-down">
        
        <% if user_signed_in? %>
        <li><a href="index">게시판</a></li>
        
         <!-- Dropdown Trigger -->
  <a class='dropdown-button btn grey darken-4' href='#' data-activates='dropdown1' style='color:#FFFFFF' data-constrainwidth="false"><%= current_user.name %></a>

  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'style='color:#ffca28'>
    <li><a href="users/edit" style='color:#ffca28'>마이페이지</a></li> 
    <li class='sign_out amber-text'><%= link_to '로그아웃', destroy_user_session_path, method: 'delete' %></li>
    <!--<li><a href="#!" style='color:#ffca28'>two</a></li>-->
    <!--<li class="divider"></li>-->
    <!--<li><a href="#!" style='color:#ffca28'>three</a></li>-->
    <!--<li><a href="#!"><i class="material-icons">view_module</i>four</a></li>-->
    <!--<li><a href="#!"><i class="material-icons">cloud</i>five</a></li>-->
  </ul>
        
        <!--<li><%= current_user.name %></li>-->
        
        <!--<div class="dropdown">-->
  <!--<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">-->
    <!--Dropdown-->
  <!--  <%= current_user.name %>-->
  <!--  <span class="caret"></span>-->
  <!--</button>-->
  <!--<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">-->
  <!--  <li><a href="#">Action</a></li>-->
  <!--  <li><a href="#">Another action</a></li>-->
  <!--  <li><a href="#">Something else here</a></li>-->
  <!--  <li role="separator" class="divider"></li>-->
  <!--  <li><a href="#">Separated link</a></li>-->
  <!--</ul>-->
<!--</div>-->
        
        
        <% else %>
        
        <li><a href="/users/sign_in">로그인</a></li>
        <li><a href="/users/sign_up">회원가입</a></li>
        <% end %>
        
    </div>
  </nav>
  
  <%= yield %>

  </body>
</html>

app/views/mypage/edit.html.erb
<div class="container">
  <h2> 회원 정보 수정</h2>
  <!--<%= resource_name.to_s.humanize %>-->
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
    <%= devise_error_messages! %>
  
    <div class="field">
      <%= f.label :이메일 %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>
  
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>
  
    <div class="field">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "off" %>
      <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
    </div>
  
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
  
    <div class="field">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off" %>
     
    </div>
    
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    
    <div class="field">
      <%= f.label :nickname %><br />
      <%= f.text_field :nickname %>
    </div>
    
    <div class="actions">
      
      <%= f.submit "Update" %>
      
    </div>
  <% end %>
  
  <h3>회원 탈퇴</h3>
  
  <p>회원 탈퇴? <%= button_to "회원 탈퇴", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
  
  <%= link_to "Back", :back %>
</div>

app/views/mypage/index.html.erb
<div class="container">
  <h2>Edit <%= resource_name.to_s.humanize %></h2>
  
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
    <%= devise_error_messages! %>
  
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>
  
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>
  
    <div class="field">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "off" %>
      <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
    </div>
  
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
  
    <div class="field">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off" %>
    </div>
    
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    
    <div class="field">
      <%= f.label :nickname %><br />
      <%= f.text_field :nickname %>
    </div>
    
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
  <% end %>
  
  <h3>Cancel my account</h3>
  
  <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
  
  <%= link_to "Back", :back %>
</div>

app/views/mypage/new.html.erb
<div class="container" style="width:400px; margin:0 auto; margin-top:30px;">
  <center><h4>회원가입</h4></center>
  
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>
  
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>
  
    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>
    
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
  
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    
    <div class="field">
      <%= f.label :nickname %><br />
      <%= f.text_field :nickname %>
    </div>
    
    <div class="actions">
      <center><%= f.submit "Signup" %></center>
    </div>
  <% end %>
  
  <%= render "devise/shared/links" %>
</div>

app/views/posts/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="card col s12" style="border-radius : 0 6em 0 6em">
          <div class="card-content">
            <%= form_tag post_path(@post), method: "patch", multipart: true do %>
            <input type="hidden" name="id" value="<%= @post.id%>">
            <!--숨겨서 값을 전달-->
              <div class="input-field">
                <%= text_area_tag :title, @post.title, class: "materialize-textarea", placeholder: "제목을 적어주세요" %>
              </div>
              
              <div class="input-field">
                <%= text_area_tag :content, @post.content, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
              </div>
              
              <div class="input-field">
                <!--<input type="file" name="image"> <br>-->
                <%= file_field_tag :image %>
              </div>
              
    
              <div class="input-field">
                <center><%= button_tag "수정하기", class: "btn" %></center>
              </div>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container" style="width:1000px; margin:0 auto; margin-top:10px;">
      <table width=1000 class="highlight">
        <thead>
          <tr>
            <th width=3% class="center-align">#</th>
            <th width=20% class="center-align">제목</th>
            <th width=20% class="center-align">내용</th>
            <th width=10% class="center-align">작성자</th>
            <th width=8% class="center-align">댓글 수</th>
            <th width=10% class="center-align">작성시간</th>
          </tr>
        </thead>
        
        <tbody>
        <!--<% post_num = @posts.count %>-->
         <% @posts.each do |post|%>
         <tr onclick="location.href='/posts/<%= post.id%>'" style="cursor:pointer;">
            <th scope="row" class="center-align"><%= post.id %></th>
            <td class="center-align"><%= post.title.truncate(20, separator: /\s/, ommission: "....") %></td>
            <td class="center-align"><%= post.content.truncate(20, separator: /\s/, ommission: "....") %></td>
            <td class="center-align"><%= post.user.nickname %></td>
            <td class="center-align"><%= post.comments.count %></td>
            <td class="center-align"><%= post.created_at %></td>
          </tr>
          <!--<% post_num-=1 %>-->
          <% end %>
        </tbody>
      </table>
      
    <div class="container">
        <div class="row justify-content-md-center">  
            <%= will_paginate @posts, renderer: MaterializePagination::Rails %>
        </div>
    </div>
    
    <div class="fixed-bottom row">
        <div class="col s12 offset-s10">
            <a class="btn-floating btn-large waves-effect waves-light amber lighten-1" href='posts/new'>
                <i class="large material-icons">mode_edit</i>
            </a>
        </div>
    </div>
    
</div>
    

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset = "utf-8">
         <!--<link rel = "stylesheet" type ="text/css" href = "/app/views/posts/style.css" />-->
         <style>
         .container {
             width: 1000px;
         }
         .writer_card {
            border: 10px solid #ffc107;
            width: 1000px;
            height: 300px;
            border-radius: 8em;
        }

        .writer_title {
            font-size:35pt;
            margin-left:55px;
            margin-top:10px;
        }
        .writer_nickname {
            font-size:12pt;
            margin-top:30px;
        }
        .content {
            font-size:13pt;
            margin-left:55px;
        }
        </style>
    </head>
    <body>
      <div class="container mt-3">
        <div class="row">
          <div class="card col s12" style="border-radius : 0 6em 0 6em">
                <div class="card-content">
                  <%= form_tag posts_path, multipart: true do %>
                    <div class="input-field">
                      <%= text_area_tag :title, nil, class: "materialize-textarea", placeholder: "제목을 적어주세요" %>
                    </div>
                    
                    <div class="input-field">
                      <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
                    </div>
                    
                    <!--<input type="file" name="image"> <br>-->
                    <%= file_field_tag 'image' %><br>
                    
                    
          
                    <div class="input-field">
                      <center><%= button_tag "작성하기", class: "btn" %></center>
                    </div>
                  <% end %>
            </div>
          </div>
        </div>
      </div>
  </body>
  </html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset = "utf-8">
         <!--<link rel = "stylesheet" type ="text/css" href = "/app/views/posts/style.css" />-->
         <style>
         .container {
             width: 1000px;
         }
         .writer_card {
            border: 7px solid #ffc107;
            width: 900px;
            height: auto;
            border-radius: 8em;
            margin-left:30px;
        }

        .writer_title {
            font-size:35pt;
            margin-left:55px;
            margin-top:10px;
        }
        .writer_nickname {
            font-size:12pt;
            margin-top:30px;
        }
        .content {
            font-size:13pt;
            margin-left:55px;
        }
        .image {
            margin-left:55px;
            margin-bottom:20px;
        }
        .comment_nickname {
            font-size:18pt
        }
        .comment_content {
            font-size:11pt;
            margin-left:25px;
        }
        .comment_icon {
             margin-left:55px;
             text-align:left; 
             margin-top:15px;
        }
        .container_custom {
            width: 850px;
            margin-left:80px;
        }
        .write_thumb {
            width: 40px;
            height: 40px;
            margin-top: 20px;
            margin-left: 5px;
        }
        </style>
    </head>
    <body>
        <div class="container mt-5">
            <div class="writer_card" style="border-radius : 0 6em 0 6em;">
                
                <div class="row">
                    <div class="col writer_title">
                      <%= @post.title%>
                    </div>
                     
                    <div class="media" height="50">
                        <% if @post.user.avatar %>
                          <img class="circle responsive-img write_thumb" src="<%= @post.user.avatar.thumb.url %>">
                        <% end %>
                    </div>
                    
                    <div class="col-md-auto writer_nickname">
                        <%= @post.user.nickname%>
                    </div>
                    
                    <div class="col col-lg-2 writer_nickname">
                      <%= @post.created_at%>
                    </div>
                 </div>
                
                <div class="mt-5 content"><%= @post.content%></div>
                <div class="mt-2 image"><img src="<%= @post.image.url %>"></div>
            
            </div>
            
            
            
            <div class="container_custom d-flex justify-content-end">
              <div class="p-2"><% if current_user.id == @post.user.id %>
                    <%= link_to "수정", edit_post_path(@post) %></div>
                <div class="p-2"><%= link_to "삭제", post_path(@post), method:"delete" %>
                <% end %>
                </div>
            </div>
            
            <div style="width:920px; text-align:right; margin-top:15px;">
                <div class="mr-auto p-2"><i class="small material-icons">insert_comment</i> &nbsp; <%= @post.comments.count %></div>
            </div>

            
            <div style="width:920px; text-align:right; margin-top:15px;">
                <%= @post.likes.size %>명이 좋아합니다.
                <% if current_user.is_like?(@post) %>
                    <i class="small material-icons">favorite</i><%= link_to "좋아요 취소", post_like_path(@post), method: "post"%>
                <% else %>
                    <i class="small material-icons">favorite_border</i><%= link_to "좋아요", post_like_path(@post), method: "post"%>
                <% end %>
            </div>
            
            <!--댓글 작성-->
            <%= form_tag post_comments_path(@post) do %>
            
            <div style="">
                <div class="input-field" style="width:600px; margin-left:50px;">
                
              </div>
              <div class="input-field" style="width:100px;">
                
              </div>
                
            </div>
            
            <div style="width:1000px;">
                <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해주세요.", required: true %>
                <%= button_tag "댓글 쓰기", class: "btn amber" %>
            </div>
            
              
            <% end %>
            
            <% if @post.comments.present? %>
              <ul class="collection">
              <% @post.comments.each do |comment| %>
                <li class="collection-item mt-3 avatar">
                        <% if comment.user.avatar %>
                        <img class="circle thumbnail" src="<%= comment.user.avatar.thumb.url %>">
                        <% end %>
                      <span class="title comment_nickname"><%= comment.user.nickname %></span>
                      <span class="right"><%= comment.created_at %></span>
                      <p class="pre-line comment_content mt-3"><%= comment.content %></p>
                      <% if comment.user.id == current_user.id %>
                        <div style="text-align:right">
                            <%= link_to "수정", edit_post_comment_path(@post, comment) %>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <%= link_to "삭제", post_comment_path(@post, comment), method: "delete" %>
                        </div>
                      <% end %>
                </li>
              <% end %>
              </ul>
            <% end %>
            
        </div>
        
    </body>
</html>